CREATE TABLE users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar not null,
    surname varchar not null,
    isadmin boolean not null,
    email varchar not null,
    password varchar not null
);